import { Router } from 'express'
import { z } from 'zod'
import { prisma } from '../db.js'
import type { Request } from 'express'
export const relationsRouter = Router({ mergeParams: true })
const input = z.object({ fromId: z.string().uuid(), toId: z.string().uuid(), type: z.enum(['FATHER', 'MOTHER', 'SPOUSE']) })
async function tree(request: Request<Record<string, string>>) { return prisma.familyTree.findFirst({ where: { id: request.params.treeId, ownerId: request.userId } }) }
const treeId = (request: Request): string => (request.params as Record<string, string>).treeId
relationsRouter.get('/', async (request, response) => { const id = treeId(request); if (!await tree(request)) return response.status(404).json({ error: 'Arbre introuvable.' }); return response.json(await prisma.relation.findMany({ where: { treeId: id } })) })
relationsRouter.post('/', async (request, response) => { const id = treeId(request); if (!await tree(request)) return response.status(404).json({ error: 'Arbre introuvable.' }); const parsed = input.safeParse(request.body); if (!parsed.success) return response.status(400).json({ error: 'Relation invalide.' }); try { return response.status(201).json(await prisma.relation.create({ data: { ...parsed.data, treeId: id } })) } catch { return response.status(409).json({ error: 'Relation déjà existante ou personnes absentes.' }) } })
relationsRouter.patch('/:relationId', async (request, response) => { const id = treeId(request); if (!await tree(request)) return response.status(404).json({ error: 'Arbre introuvable.' }); const parsed = input.partial().safeParse(request.body); if (!parsed.success) return response.status(400).json({ error: 'Relation invalide.' }); const existing = await prisma.relation.findFirst({ where: { id: request.params.relationId, treeId: id } }); if (!existing) return response.status(404).json({ error: 'Relation introuvable.' }); try { return response.json(await prisma.relation.update({ where: { id: existing.id }, data: parsed.data })) } catch { return response.status(409).json({ error: 'Relation déjà existante ou personnes absentes.' }) } })
relationsRouter.delete('/:relationId', async (request, response) => { const id = treeId(request); if (!await tree(request)) return response.status(404).json({ error: 'Arbre introuvable.' }); const existing = await prisma.relation.findFirst({ where: { id: request.params.relationId, treeId: id } }); if (!existing) return response.status(404).json({ error: 'Relation introuvable.' }); await prisma.relation.delete({ where: { id: existing.id } }); return response.status(204).send() })
