"""add tree_membership, person, relationship tables

Revision ID: 942f407159d1
Revises: b112346e58db
Create Date: 2026-09-13 22:46:16.494679

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '942f407159d1'
down_revision: Union[str, Sequence[str], None] = 'b112346e58db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('person',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tree_id', sa.Uuid(), nullable=False),
    sa.Column('first_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('last_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('gender', sa.Enum('male', 'female', 'other', 'unknown', name='gender'), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('death_date', sa.Date(), nullable=True),
    sa.Column('birth_place', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('photo_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('linked_user_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['linked_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['tree_id'], ['tree.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_person_tree_id'), 'person', ['tree_id'], unique=False)
    op.create_table('treemembership',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tree_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.Enum('owner', 'editor', 'viewer', name='membershiprole'), nullable=False),
    sa.Column('invited_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tree_id'], ['tree.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_treemembership_tree_id'), 'treemembership', ['tree_id'], unique=False)
    op.create_index(op.f('ix_treemembership_user_id'), 'treemembership', ['user_id'], unique=False)
    op.create_table('relationship',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tree_id', sa.Uuid(), nullable=False),
    sa.Column('person_a_id', sa.Uuid(), nullable=False),
    sa.Column('person_b_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.Enum('parent_child', 'spouse', 'partner', name='relationshiptype'), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['person_a_id'], ['person.id'], ),
    sa.ForeignKeyConstraint(['person_b_id'], ['person.id'], ),
    sa.ForeignKeyConstraint(['tree_id'], ['tree.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_relationship_person_a_id'), 'relationship', ['person_a_id'], unique=False)
    op.create_index(op.f('ix_relationship_person_b_id'), 'relationship', ['person_b_id'], unique=False)
    op.create_index(op.f('ix_relationship_tree_id'), 'relationship', ['tree_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_relationship_tree_id'), table_name='relationship')
    op.drop_index(op.f('ix_relationship_person_b_id'), table_name='relationship')
    op.drop_index(op.f('ix_relationship_person_a_id'), table_name='relationship')
    op.drop_table('relationship')
    op.drop_index(op.f('ix_treemembership_user_id'), table_name='treemembership')
    op.drop_index(op.f('ix_treemembership_tree_id'), table_name='treemembership')
    op.drop_table('treemembership')
    op.drop_index(op.f('ix_person_tree_id'), table_name='person')
    op.drop_table('person')
    # ### end Alembic commands ###
