import type { LifeEvent, Person, Sex } from '../types/family'
import { getSpouseIds } from './family'

const gedcomDate = (value?: string): string | undefined => { if (!value) return undefined; const parts = value.trim().split(/\s+/); if (parts.length === 1 && /^\d{4}$/.test(parts[0])) return `${parts[0]}-01-01`; const months: Record<string, string> = { JAN: '01', FEB: '02', MAR: '03', APR: '04', MAY: '05', JUN: '06', JUL: '07', AUG: '08', SEP: '09', OCT: '10', NOV: '11', DEC: '12' }; if (parts.length >= 3 && months[parts[1]]) return `${parts[2]}-${months[parts[1]]}-${parts[0].padStart(2, '0')}`; return undefined }
const gedcomFormatDate = (value?: string): string => { if (!value) return ''; const [year, month, day] = value.split('-'); const months = ['', 'JAN', 'FEB', 'MAR', 'APR', 'MAY', 'JUN', 'JUL', 'AUG', 'SEP', 'OCT', 'NOV', 'DEC']; return `${day} ${months[Number(month)]} ${year}` }
const clean = (value: string): string => value.replace(/[\r\n]/g, ' ').trim()

export function exportGedcom(people: Person[]): string {
  const ids = new Map(people.map((person, index) => [person.id, `I${index + 1}`])); const lines = ['0 HEAD', '1 SOUR Arbre familial', '1 GEDC', '2 VERS 5.5.1']
  people.forEach((person) => { lines.push(`0 @${ids.get(person.id)}@ INDI`, `1 NAME ${clean(person.firstName)} /${clean(person.lastName)}/`, `1 SEX ${person.sex === 'female' ? 'F' : person.sex === 'male' ? 'M' : 'U'}`); if (person.birthDate || person.birthPlace) { lines.push('1 BIRT'); if (person.birthDate) lines.push(`2 DATE ${gedcomFormatDate(person.birthDate)}`); if (person.birthPlace) lines.push(`2 PLAC ${clean(person.birthPlace)}`) } if (person.deathDate || person.deathPlace) { lines.push('1 DEAT'); if (person.deathDate) lines.push(`2 DATE ${gedcomFormatDate(person.deathDate)}`); if (person.deathPlace) lines.push(`2 PLAC ${clean(person.deathPlace)}`) } if (person.profession) lines.push(`1 OCCU ${clean(person.profession)}`); if (person.notes) lines.push(`1 NOTE ${clean(person.notes)}`); (person.events ?? []).forEach((event) => { if (event.type === 'birth' || event.type === 'death') return; lines.push('1 EVEN', `2 TYPE ${clean(event.title)}`); if (event.date) lines.push(`2 DATE ${gedcomFormatDate(event.date)}`); if (event.place) lines.push(`2 PLAC ${clean(event.place)}`); if (event.description) lines.push(`2 NOTE ${clean(event.description)}`) }) })
  let familyIndex = 1; const familyKeys = new Set<string>(); people.forEach((person) => { getSpouseIds(person).forEach((spouseId) => { const spouse = people.find((candidate) => candidate.id === spouseId); if (!spouse) return; const key = [person.id, spouse.id].sort().join('|'); if (familyKeys.has(key)) return; familyKeys.add(key); lines.push(`0 @F${familyIndex++}@ FAM`, `1 HUSB @${ids.get(person.sex === 'male' ? person.id : spouse.id)}@`, `1 WIFE @${ids.get(person.sex === 'female' ? person.id : spouse.id)}@`); people.filter((child) => child.fatherId === person.id || child.motherId === person.id || child.fatherId === spouse.id || child.motherId === spouse.id).forEach((child) => lines.push(`1 CHIL @${ids.get(child.id)}@`)) }) }); lines.push('0 TRLR'); return lines.join('\n')
}

export function parseGedcom(text: string): Person[] {
  interface Raw { id: string; firstName: string; lastName: string; sex: Sex; birthDate?: string; deathDate?: string; birthPlace?: string; deathPlace?: string; profession?: string; notes?: string; events: LifeEvent[] }
  const raw = new Map<string, Raw>(); const families: { spouses: string[]; children: string[]; marriage?: string; divorce?: string; marriagePlace?: string; divorcePlace?: string }[] = []; let current: Raw | null = null; let family: typeof families[number] | null = null; let event: 'birth' | 'death' | null = null; let familyEvent: 'marriage' | 'divorce' | null = null
  for (const line of text.split(/\r?\n/)) { const match = line.match(/^(\d+)\s+(?:(@[^@]+@)\s+)?(\S+)(?:\s+(.*))?$/); if (!match) continue; const level = Number(match[1]); const pointer = match[2]; const tag = match[3]; const value = match[4]?.trim() ?? ''
    if (level === 0 && pointer && tag === 'INDI') { current = { id: pointer, firstName: '', lastName: '', sex: 'other', events: [] }; raw.set(pointer, current); family = null; event = null; continue }
    if (level === 0 && pointer && tag === 'FAM') { family = { spouses: [], children: [] }; families.push(family); current = null; event = null; continue }
    if (family && level === 1) { if (tag === 'HUSB' || tag === 'WIFE') family.spouses.push(value); if (tag === 'CHIL') family.children.push(value); if (tag === 'MARR') familyEvent = 'marriage'; if (tag === 'DIV') familyEvent = 'divorce'; continue }
    if (family && level === 2 && familyEvent) { if (tag === 'DATE') { if (familyEvent === 'marriage') family.marriage = gedcomDate(value); else family.divorce = gedcomDate(value) } if (tag === 'PLAC') { if (familyEvent === 'marriage') family.marriagePlace = value; else family.divorcePlace = value } continue }
    if (!current) continue
    if (level === 1) { event = tag === 'BIRT' ? 'birth' : tag === 'DEAT' ? 'death' : null; if (tag === 'NAME') { const name = value.match(/^(.*?)\s*\/(.*?)\//); current.firstName = name?.[1]?.trim() ?? value; current.lastName = name?.[2]?.trim() ?? '' } else if (tag === 'SEX') current.sex = value === 'F' ? 'female' : value === 'M' ? 'male' : 'other'; else if (tag === 'OCCU') current.profession = value; else if (tag === 'NOTE') current.notes = value; continue }
    if (level === 2 && event) { if (tag === 'DATE') current[`${event}Date`] = gedcomDate(value); if (tag === 'PLAC') current[`${event}Place`] = value }
  }
  const people: Person[] = [...raw.values()].map((person) => ({ id: crypto.randomUUID(), firstName: person.firstName || 'Inconnu', lastName: person.lastName, birthDate: person.birthDate ?? '', deathDate: person.deathDate, sex: person.sex, birthPlace: person.birthPlace, deathPlace: person.deathPlace, profession: person.profession, notes: person.notes, events: person.events, spouseIds: [] }))
  const pointerToId = new Map<string, string>([...raw.keys()].map((pointer, index) => [pointer, people[index].id])); const byId = new Map(people.map((person) => [person.id, person]))
  families.forEach((fam) => { const spouses = fam.spouses.map((pointer) => pointerToId.get(pointer)).filter((id): id is string => Boolean(id)); spouses.forEach((id) => { const person = byId.get(id); if (!person) return; person.spouseIds = [...new Set([...(person.spouseIds ?? []), ...spouses.filter((other) => other !== id)])]; if (fam.marriage) person.events = [...(person.events ?? []), { id: crypto.randomUUID(), type: 'marriage', title: 'Mariage', date: fam.marriage, place: fam.marriagePlace }]; if (fam.divorce) person.events = [...(person.events ?? []), { id: crypto.randomUUID(), type: 'divorce', title: 'Divorce', date: fam.divorce, place: fam.divorcePlace }] }); fam.children.forEach((childPointer) => { const child = byId.get(pointerToId.get(childPointer) ?? ''); if (!child) return; spouses.forEach((parentId) => { const parent = byId.get(parentId); if (parent?.sex === 'male' && !child.fatherId) child.fatherId = parentId; if (parent?.sex === 'female' && !child.motherId) child.motherId = parentId }) }) })
  return people
}
